name: ❓ Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Before asking a question, please:
        - Check the [README](https://github.com/kuasar-mknd/visualdon-projet/blob/main/README.md)
        - Search [existing discussions](https://github.com/kuasar-mknd/visualdon-projet/discussions)
        - Look through [closed issues](https://github.com/kuasar-mknd/visualdon-projet/issues?q=is%3Aissue+is%3Aclosed)

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation & Setup
        - Usage & Features
        - Data & Sources
        - Development & Contributing
        - Deployment
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any relevant background information, what you've tried, or related documentation
      placeholder: I tried... but...

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Your environment details, if applicable
      placeholder: |
        - Node version: 20.x
        - npm version: 10.x
        - OS: macOS 14
